// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteAccountEntry(ctx context.Context, accountID int64) error
	DeleteEntry(ctx context.Context, id int64) error
	DeleteFromAccountTransfer(ctx context.Context, fromAccountID int64) error
	DeleteToAccountTransfer(ctx context.Context, toAccountID int64) error
	DeleteTransfer(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAccount(ctx context.Context, arg ListAccountParams) ([]Account, error)
	ListEntry(ctx context.Context, arg ListEntryParams) ([]Entry, error)
	ListFRomAccountTransfers(ctx context.Context, arg ListFRomAccountTransfersParams) ([]Transfer, error)
	ListToAccountTransfers(ctx context.Context, arg ListToAccountTransfersParams) ([]Transfer, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
